name: boilerplate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  connectivity_plus: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  pinput: ^5.0.2
  flutter_bloc: ^9.1.1
  awesome_dialog: ^3.2.1
  dio: ^5.9.0
  lottie: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_theme_icon.png
    - assets/images/app_splash.png
    - assets/images/background_image.png
    - assets/images/background_type_1.png
    - assets/images/success_icon.png
    - assets/images/sub_background.png
    - assets/images/illustrations_first.png
    - assets/images/illustrations_second.png
    - assets/images/illustrations_third.png
    - assets/images/app_logo_black.png
    - assets/images/app_name_logo.png
    - assets/images/huawei.png
    - assets/images/iphone.png
    - assets/images/location.png
    - assets/images/menu.png
    - assets/images/brands/google_pixel.png
    - assets/images/brands/huawel.png
    - assets/images/brands/mi.png
    - assets/images/brands/infinix.png
    - assets/images/brands/iphone_brand.png
    - assets/images/brands/iqoo.png
    - assets/images/brands/motorola.png
    - assets/images/brands/oneplus.png
    - assets/images/brands/oppo.png
    - assets/images/brands/realme.png
    - assets/images/brands/samsung_brand.png
    - assets/images/brands/vivo.png
    - assets/images/notification.png
    - assets/images/phone_ad.png
    - assets/images/phone_card.png
    - assets/images/samsung.png
    - assets/images/left_arrow.png
    - assets/images/right_arrow.png
    - assets/images/sub_background.png
    - assets/images/instant_payment.png
    - assets/images/best_price.png
    - assets/images/door_step.png
    - assets/images/simple.png
    - assets/images/factory.png
    - assets/images/quote.png
    - assets/images/right_arrow_black.png
    - assets/images/filter.png
    - assets/images/imel.png
    - assets/images/search.png
    - assets/images/left_arrow.png
    - assets/images/valid_purchase.png
    - assets/gifs/Success.json
    - assets/images/brands/iphone_brand.png
    - assets/images/question/scratch_1.png
    - assets/images/question/lines_1.png
    - assets/images/question/unchecked_checkbox.png
    - assets/images/question/dent_1.png
    - assets/images/question/panel_1.png
    - assets/images/selected_checkbox.png



  fonts:
    - family: Modelica
      fonts:
        - asset: assets/fonts/BwModelica-Regular.otf
        - asset: assets/fonts/BwModelica-Medium.otf
        - asset: assets/fonts/BwModelica-Bold.otf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
